apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: dev
spec:
  type: NodePort
  selector:
    app: playground
  ports:
    - name: http
      port: 80
      targetPort: 8888
      nodePort: 38888
