apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: dev
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - name: http
      port: 80
      targetPort: 8888
  type: ClusterIP